// GET Collections namespace = Abilities, collection = test_collection

# curl --request GET
#  --url # curl -X GET "https://b769ec4a-2a5a-4338-a990-fb943f7d4086-us-east-1.apps.astra.datastax.com/api/rest/v2/namespaces/Abilities/collections/test_collection"
#  -H  "X-Cassandra-Token: AstraCS:WWzsOMzGhSTlUDgjFFrfXMMT:b43cf40a0d76e24f4f7ace77f2f5514206387ef4e2d53b0ad8ac55ce34a0906b"
#  -H  "accept: application/json"
GET https://b769ec4a-2a5a-4338-a990-fb943f7d4086-us-east-1.apps.astra.datastax.com/api/rest/v2/namespaces/Abilities/collections/test_collection/6faffe53-b5e1-49ee-a940-7c14ce3c4250
X-Cassandra-Token: AstraCS:WWzsOMzGhSTlUDgjFFrfXMMT:b43cf40a0d76e24f4f7ace77f2f5514206387ef4e2d53b0ad8ac55ce34a0906b
Content-Type: application/json

###

